set(RGB_LCD_DEVICE_FILES "")
set(RGB_LCD_PATH src/lcd/rgb)

if (CONFIG_LCD_GC9503V)
	list(APPEND RGB_LCD_DEVICE_FILES ${RGB_LCD_PATH}/lcd_gc9503v.c)
endif()

if (CONFIG_LCD_H050IWV)
	list(APPEND RGB_LCD_DEVICE_FILES ${RGB_LCD_PATH}/lcd_h050iwv.c)
endif()

if (CONFIG_LCD_HX8282)
	list(APPEND RGB_LCD_DEVICE_FILES ${RGB_LCD_PATH}/lcd_hx8282.c)
endif()

if (CONFIG_LCD_MD0430R)
	list(APPEND RGB_LCD_DEVICE_FILES ${RGB_LCD_PATH}/lcd_md0430r.c)
endif()

if (CONFIG_LCD_MD0700R)
	list(APPEND RGB_LCD_DEVICE_FILES ${RGB_LCD_PATH}/lcd_md0700r.c)
endif()

if (CONFIG_LCD_NT35512)
	list(APPEND RGB_LCD_DEVICE_FILES ${RGB_LCD_PATH}/lcd_nt35512.c)
endif()

if (CONFIG_LCD_NT35510)
	list(APPEND RGB_LCD_DEVICE_FILES ${RGB_LCD_PATH}/lcd_nt35510.c)
endif()

if (CONFIG_LCD_ST7282)
	list(APPEND RGB_LCD_DEVICE_FILES ${RGB_LCD_PATH}/lcd_st7282.c)
endif()


if (CONFIG_LCD_ST7701S_LY)
	list(APPEND RGB_LCD_DEVICE_FILES ${RGB_LCD_PATH}/lcd_st7701s_ly.c)
endif()

if (CONFIG_LCD_ST7701S)
	list(APPEND RGB_LCD_DEVICE_FILES ${RGB_LCD_PATH}/lcd_st7701s.c)
endif()

if (CONFIG_LCD_ST7701SN)
	list(APPEND RGB_LCD_DEVICE_FILES ${RGB_LCD_PATH}/lcd_st7701sn.c)
endif()

if (CONFIG_LCD_AML01)
	list(APPEND RGB_LCD_DEVICE_FILES ${RGB_LCD_PATH}/lcd_aml01.c)
endif()