set(DVP_CAMERA_DEVICE_FILES "")
set(DVP_CAMERA_PATH src/dvp)

if (CONFIG_DVP_CAMERA)
	list(APPEND DVP_CAMERA_DEVICE_FILES ${DVP_CAMERA_PATH}/dvp_sensor_devices.c)
endif()

if (CONFIG_DVP_CAMERA)
	list(APPEND DVP_CAMERA_DEVICE_FILES ${DVP_CAMERA_PATH}/dvp_gc0308.c)
endif()

if (CONFIG_DVP_CAMERA)
	list(APPEND DVP_CAMERA_DEVICE_FILES ${DVP_CAMERA_PATH}/dvp_gc0328c.c)
endif()

if (CONFIG_DVP_CAMERA)
	list(APPEND DVP_CAMERA_DEVICE_FILES ${DVP_CAMERA_PATH}/dvp_gc2145.c)
endif()

if (CONFIG_DVP_CAMERA)
	list(APPEND DVP_CAMERA_DEVICE_FILES ${DVP_CAMERA_PATH}/dvp_hm1055.c)
endif()

if (CONFIG_DVP_CAMERA)
	list(APPEND DVP_CAMERA_DEVICE_FILES ${DVP_CAMERA_PATH}/dvp_ov2640.c)
endif()

if (CONFIG_DVP_CAMERA)
	list(APPEND DVP_CAMERA_DEVICE_FILES ${DVP_CAMERA_PATH}/dvp_sc101.c)
endif()
