SDK_DIR := $(abspath ../../..)

PROJECT_MAKE_FILE := $(SDK_DIR)/bk_idk/tools/build_tools/build_files/project_main.mk
ifeq ($(wildcard $(PROJECT_MAKE_FILE)),)
    $(error "$(PROJECT_MAKE_FILE) not exist, please check sdk directory.")
endif
include $(PROJECT_MAKE_FILE)
